---

- name: HIGH | RHEL-10-001000 | AUDIT | RHEL 10 must be a vendor-supported release.
  when: rhel10stig_001000
  tags:
    - RHEL-10-001000
    - CAT1
    - CCI-003376
    - SRG-OS-000830-GPOS-00300
    - SV-282965r1197252_rule
    - V-282965
    - NIST800-53R4_CM-6
  block:
    - name: HIGH | RHEL-10-001000 | AUDIT | RHEL-10-001000 | RHEL 10 must be a vendor-supported release. | Check if RHEL 10 is a vendor-supported release.
      when: ansible_facts['distribution_version'] is ansible.builtin.version_compare(rhel10stig_min_supported_os_ver, '>=')
      ansible.builtin.debug:
        msg: "RHEL 10 is a vendor-supported release. {{ ansible_facts['distribution_version'] }}"

    - name: HIGH | RHEL-10-001000 | AUDIT | RHEL-10-001000 | RHEL 10 must be a vendor-supported release. | Check if RHEL 10 is a vendor-supported release.
      when: ansible_facts['distribution_version'] is not ansible.builtin.version_compare(rhel10stig_min_supported_os_ver, '>=')
      ansible.builtin.debug:
        msg: "Warning!!! RHEL 10 is not a vendor-supported release. {{ ansible_facts['distribution_version'] }}"

    - name: HIGH | RHEL-10-001000 | AUDIT | RHEL-10-001000 | RHEL 10 must be a vendor-supported release. | Check if RHEL 10 is a vendor-supported release.
      when: ansible_facts['distribution_version'] is not ansible.builtin.version_compare(rhel10stig_min_supported_os_ver, '>=')
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: "HIGH | RHEL-10-001000"

- name: HIGH | RHEL-10-001030 | PATCH | RHEL 10 must check the GPG signature of software packages originating from external software repositories before installation.
  when: rhel10stig_001030
  tags:
    - RHEL-10-001030
    - CAT1
    - CCI-NA
    - SRG-OS-000366-GPOS-00153
    - SV-280932r1197215_rule
    - V-257820
    - NIST800-NA
    - dnf
    - packages
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^gpgcheck
    line: gpgcheck=1
    state: present

- name: HIGH | RHEL-10-001040 | PATCH | RHEL 10 must check the GPG signature of locally installed software packages before installation.
  when: rhel10stig_001040
  tags:
    - RHEL-10-001040
    - CAT1
    - CCI-001749
    - SRG-OS-000366-GPOS-00153
    - SV-257821r1015077_rule
    - V-257821
    - NIST800-53R4_CM-5
    - dnf
    - packages
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^localpkg_gpgcheck
    line: localpkg_gpgcheck=1

- name: HIGH | RHEL-10-001050 | PATCH | RHEL 10 must check the GPG signature of locally installed software packages before installation.
  when: rhel10stig_001050
  tags:
    - RHEL-10-001050
    - CAT1
    - CCI-NA
    - SRG-OS-000366-GPOS-00153
    - SV-280933r1197217_rule
    - V-280933
    - NIST800-NA
    - dnf
    - packages
  block:
    - name: HIGH | RHEL-10-001050 | PATCH | RHEL 10 must check the GPG signature of locally installed software packages before installation. | find repo files
      ansible.builtin.find:
        path: /etc/yum.repos.d
        patterns: "*.repo"
        use_regex: true
        contains: gpgcheck
        file_type: file
      register: discovered_repo_list

    - name: HIGH | RHEL-10-001050 | PATCH | RHEL 10 must check the GPG signature of locally installed software packages before installation. | Set gpgcheck
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: ^gpgcheck
        replace: gpgcheck=1
      loop: "{{ discovered_repo_list.files }}"
